[package]
name = "import_ranking_component_image"
version = "0.1.0"
authors = ["Toshiyuki Ihara <toshiyuki.ihara@noin.tv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
rust = "0.0.1"